title: Soft City
description: An indie game studio
# baseurl: "/softcitysite"
baseurl: ""

url: "https://cxmi.github.io"

# If your repo is username.github.io leave baseurl as ""
# If your repo is username.github.io/reponame set baseurl: "/reponame"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock